"""empty message

Revision ID: fae3ec329f9f
Revises: 40a02b96e451
Create Date: 2021-01-06 10:03:20.394161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fae3ec329f9f'
down_revision = '40a02b96e451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('salt', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plz', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plz')
    )
    op.create_table('ort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ort', sa.String(length=45), nullable=False),
    sa.Column('fk_plz', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_plz'], ['plz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ort')
    )
    op.create_table('kunden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma', sa.String(length=45), nullable=False),
    sa.Column('ansprechsperson', sa.String(length=45), nullable=True),
    sa.Column('adresse', sa.String(length=100), nullable=False),
    sa.Column('plzort', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['plzort'], ['ort.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma')
    )
    op.create_table('mitarbeiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=45), nullable=False),
    sa.Column('nachname', sa.String(length=45), nullable=False),
    sa.Column('adresse', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('fk_ort', sa.Integer(), nullable=False),
    sa.Column('ahv', sa.String(length=45), nullable=False),
    sa.Column('telnr', sa.String(length=45), nullable=False),
    sa.Column('gebdat', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fk_ort'], ['ort.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ahv'),
    sa.UniqueConstraint('email')
    )
    op.create_table('baustellen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baustelle', sa.String(length=45), nullable=False),
    sa.Column('fk_kunde', sa.Integer(), nullable=True),
    sa.Column('adresse', sa.String(length=100), nullable=False),
    sa.Column('fk_ort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_kunde'], ['kunden.id'], ),
    sa.ForeignKeyConstraint(['fk_ort'], ['ort.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baustelle')
    )
    op.create_table('rapport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_mitarbeiter', sa.Integer(), nullable=False),
    sa.Column('fk_kunde', sa.Integer(), nullable=False),
    sa.Column('fk_baustelle', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('stunden', sa.Float(), nullable=False),
    sa.Column('arbeit', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fk_baustelle'], ['baustellen.id'], ),
    sa.ForeignKeyConstraint(['fk_kunde'], ['kunden.id'], ),
    sa.ForeignKeyConstraint(['fk_mitarbeiter'], ['mitarbeiter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.drop_table('rapport')
    op.drop_table('baustellen')
    op.drop_table('mitarbeiter')
    op.drop_table('kunden')
    op.drop_table('ort')
    op.drop_table('plz')
    op.drop_table('login')
    # ### end Alembic commands ###
